name: Update clasp.json

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  update-clasp-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Update clasp.json
        run: node update-clasp-json.js

      - name: Commit changes
        run: |
          git config --global user.email "anuj@pw.live"
          git config --global user.name "anuj-pw"
          git add .
          git commit -m "Update .clasp.json"
          git push
